baseurl = "https://matthewcieplak.com/"
title = "Matthew Cieplak"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
# disqusShortname = "matthewcieplak"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-59205527-2"
preserveTaxonomyNames = true
paginate = 6 #frontpage pagination

[params]
  slogan = "Internet impresario"
  description = "Web development, DIY electronics, and funky disco music." # meta description
  #author = "Göran Svensson"
  #authorLink = "https://appernetic.io/"
  bio = [
    ""
  ]
  copyright = [
    "&copy; 2022 Matthew Cieplak",
    "Based on Nederburg Hugo Theme by [Appernetic](https://appernetic.io)."
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "goran@molnsys.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

#  [[menu.main]]
#  name = "Curriculum Vitae"
#  url = "cv/"
#  weight = 3

  [[menu.main]]
  name = "Contact"
  url = "mailto:matthew.cieplak@gmail.com"
  weight = 4

  [params.social]
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  soundcloud    = "https://soundcloud.com/extralifedisco"
  email         = "matthew.cieplak@gmail.com"
  twitter       = "http://twitter.com/extralifedisco"
  #linkedin      = "full profile url in linkedin"
  #stackoverflow = "full profile url in stackoverflow"
  instagram     = "http://instagram.com/extralifedisco"
  github        = "http://github.com/matthewcieplak"
  #pinterest     = "full profile url in pinterest"

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true